# tomcat configuration
server:
  port: 8080
  servlet :
    context-path:



# mybatis configuration
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-scripting-language:

# database configuration
spring.datasource:
  url: jdbc:mysql://localhost:3306/myappdb?serverTimezone=GMT%2B8
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver

club:
  dlblog:
    page:
      enabled: false